# Generated by Django 4.1.7 on 2023-03-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_post_options_post_created_at_post_qr_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
